#define EC_RISING		0x0
#define EC_FALLING		0x1
#define EC_ABS_MODE		0x0
#define EC_DELTA_MODE	0x1
#define EC_DIV1			0x0
#define EC_CONTINUOUS	0x0
#define EC_ONESHT		0x1
#define EC_ENABLE		0x1
#define EC_DISABLE		0x0
#define EC_CAP_MODE		0x0
#define EC_SYNCO_DIS	0x2
#define EC_RUN			0x1
